export const CERTIFICATIONS = [
  {
    id: 1,
    name: "Java (Basic)",
    issuer: "HackerRank",
    image: "/Java.jpg",
    issueDate: "05 Aug, 2024",
    credentialId: "138B6E7732D7",
  },
  {
    id: 2,
    name: "Python Full Stack",
    issuer: "EduSkills Academy",
    image: "/Python.jpg",
    issueDate: "1 Dec, 2024",
    credentialId: "5ee9372495733fcedb63073807b3e1f3",
  },
  {
    id: 3,
    name: "Introduction to CISSP Security Assessment & Testing and Security Operations",
    issuer: "Simplilearn SkillUp",
    image: "/CISSP.jpg",
    issueDate: "31st March 2025",
    credentialId: "8120655",
  },
  {
    id: 4,
    name: "Problem Solving (Basic)",
    issuer: "HackerRank",
    image: "/Problem_Solving.jpg",
    issueDate: "17 Apr, 2025",
    credentialId: "2F15580B3304",
  },
  {
    id: 5,
    name: "Software Engineer",
    issuer: "HackerRank",
    image: "/Software_Engineer.jpg",
    issueDate: "01 Aug, 2025",
    credentialId: "C92ABAC001BD",
  },
  {
    id: 6,
    name: "JavaScript (Intermediate)",
    issuer: "HackerRank",
    image: "/Javascript.jpg",
    issueDate: "08 Aug, 2025",
    credentialId: "589C20D374D3",
  },

  {
    id: 7,
    name: "Data Analysis with Python",
    issuer: "IBM / Coursera",
    image: "/Data Analysis.jpg",
    issueDate: "Aug 11, 2025",
    credentialId: "cad19d3e-2b24-424a-bf5e-2c56de2b043f",
  },
];