import { PERSONAL } from "./personal"

export const SEO = {
  title: `${PERSONAL.name} - ${PERSONAL.jobTitle}`,
  description: `${PERSONAL.shortBio}. Experienced developer specializing in modern web technologies, React, Next.js, and full-stack development.`,
  url: "https://shivanshrastogi.vercel.app", // Update this with your actual domain
  image: "/opengraph-image",
  keywords: [
    "full-stack developer",
    "react developer",
    "next.js developer",
    "typescript",
    "web development",
    "software engineer",
    "shivansh rastogi",
    "frontend developer",
    "backend developer",
    "javascript",
    "node.js",
    "portfolio",
    "bhubaneswar developer",
    "india developer",
    "shivansh rastogi portfolio",
    "portfolio website",
    "personal website",
    "shivansh rastogi personal website",

    "web developer",
    "react.js developer",
    "next.js portfolio developer",
    "frontend engineer",
    "backend engineer",
    "mern stack developer",
    "mean stack developer",
    "full stack engineer",
    "javascript developer",
    "typescript developer",
    "node.js developer",
    "express.js developer",
    "mongodb developer",
    "postgresql developer",
    "mysql developer",
    "sql developer",
    "graphql developer",
    "rest api developer",
    "api integration developer",
    "software development engineer",
    "software engineer portfolio",
    "software engineering student",
    "computer science engineer",
    "kiit university developer",
    "bhubaneswar programmer",
    "india software developer",
    "indian full stack developer",
    "software developer portfolio",
    "software projects developer",
    "ui developer",
    "ux developer",
    "react frontend developer",
    "next.js website developer",
    "vite developer",
    "styled-components developer",
    "tailwind css developer",
    "vercel projects developer",
    "frontend portfolio developer",
    "backend portfolio developer",
    "react projects portfolio",
    "next.js projects portfolio",
    "javascript projects portfolio",

    "shivansh rastogi developer",
    "shivansh rastogi full stack",
    "shivansh rastogi react developer",
    "shivansh rastogi next.js developer",
    "shivansh rastogi frontend developer",
    "shivansh rastogi backend developer",
    "shivansh rastogi software engineer",
    "shivansh rastogi website",
    "shivansh rastogi portfolio website",
    "shivansh rastogi github projects",
    "shivansh rastogi linkedin",
    "personal portfolio website india",
    "developer portfolio india",
    "web developer portfolio bhubaneswar",
    "software engineer portfolio india",
    "coding portfolio website",
    "programming portfolio website",
    "full stack portfolio website",
    "javascript portfolio website",
    "next.js portfolio template",
    "react portfolio template",

    "kiit university bhubaneswar",
    "btech computer science student",
    "btech software engineering student",
    "computer science undergraduate india",
    "computer science student portfolio",
    "engineering student portfolio",
    "kiit bhubaneswar developer",
    "btech 2026 graduate",
    "masters in computer science germany aspirant",
    "study abroad after btech",
    "germany ms computer science aspirant",
    "cs engineering student projects",

    "real estate app developer",
    "social media app developer",
    "crypto tracker web app",
    "dice game react project",
    "twitter bio generator app",
    "full stack project showcase",
    "web app developer india",
    "modern web app developer",
    "personal projects developer",
    "software side projects",
    "student developer portfolio",
    "frontend projects showcase",
    "backend projects showcase",
    "react next.js portfolio projects",
    "python full stack projects",
    "open source contributor",
    "github portfolio developer",

    "github developer portfolio",
    "git version control",
    "docker developer",
    "aws cloud developer",
    "vercel hosting developer",
    "firebase developer",
    "neon database developer",
    "prisma orm developer",
    "fastapi developer",
    "python developer",
    "java developer",
    "java programming portfolio",
    "data structures developer",
    "algorithms developer",
    "microsoft office specialist certification",
    "ibm data analysis with python",
    "machine learning beginner portfolio",
    "data science beginner portfolio",

    "software developer bhubaneswar",
    "full stack developer bhubaneswar",
    "react developer bhubaneswar",
    "next.js developer bhubaneswar",
    "javascript developer bhubaneswar",
    "frontend developer bhubaneswar",
    "backend developer bhubaneswar",
    "software engineer bhubaneswar",
    "kiit university developer bhubaneswar",
    "orissa developer portfolio",
    "odisha software engineer",
    "india full stack developer",
    "india web developer",
    "india portfolio website",
    "developer from india",

    "sports and coding developer",
    "tech enthusiast india",
    "gamer and developer portfolio",
    "cricket enthusiast developer",
    "student leader developer",
    "adaptable developer portfolio",
    "problem solving coder",
    "tech blogger india",
    "coding vlogger india",
    "software engineering student achievements"
  ]
}
